CREATE TABLE "billing-app4_oauth_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing-app4_oauth_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"provider" varchar(50) NOT NULL,
	"refreshToken" text NOT NULL,
	"accessToken" text,
	"expiresAt" timestamp with time zone,
	"scope" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "billing-app4_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing-app4_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "billing-app4_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "billing-app4_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"clerkId" varchar(256) NOT NULL,
	CONSTRAINT "billing-app4_user_clerkId_unique" UNIQUE("clerkId")
);
--> statement-breakpoint
ALTER TABLE "billing-app4_oauth_token" ADD CONSTRAINT "billing-app4_oauth_token_userId_billing-app4_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."billing-app4_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "oauth_token_user_provider_idx" ON "billing-app4_oauth_token" USING btree ("userId","provider");--> statement-breakpoint
CREATE INDEX "name_idx" ON "billing-app4_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_name_idx" ON "billing-app4_user" USING btree ("name");