import Head from "next/head";
import { Calendar } from "~/components/ui/calendar";
import { type DateRange } from "react-day-picker";

import { api } from "~/utils/api";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import { Card, CardContent } from "~/components/ui/card";
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { EventCard } from "~/components/EventCard";

export default function Home() {
  const { mutate: authWithGoogleCalendar } =
    api.user.authWithGoogleCalendar.useMutation();

  const [dateRange, setDateRange] = useState<DateRange | undefined>({
    from: new Date(2025, 10, 23),
    to: new Date(2025, 10, 30),
  });

  const { data: events } = api.workflow.getEvents.useQuery(
    dateRange?.from && dateRange?.to
      ? { startDate: dateRange.from, endDate: dateRange.to }
      : undefined,
    { enabled: !!dateRange?.from && !!dateRange?.to },
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex h-16 items-center justify-end gap-4 p-4">
        <SignedOut>
          <SignInButton />
          <SignUpButton>
            <button className="h-10 cursor-pointer rounded-full bg-[#6c47ff] px-4 text-sm font-medium text-white sm:h-12 sm:px-5 sm:text-base">
              Sign Up
            </button>
          </SignUpButton>
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </header>

      <main className="container mx-auto max-w-6xl p-4">
        <div className="mb-6 flex flex-col gap-4">
          <Calendar
            mode="range"
            defaultMonth={dateRange?.from}
            selected={dateRange}
            onSelect={setDateRange}
            className="rounded-lg border shadow-sm"
          />
          <Button
            onClick={() => {
              authWithGoogleCalendar(undefined, {
                onSuccess: (data) => window.open(data.url, "_blank"),
              });
              console.log("hi");
            }}
          >
            Google
          </Button>
        </div>

        <div className="space-y-4">
          <h2 className="text-2xl font-bold">Events</h2>
          <div className="flex gap-4 w-full">
            <div className="flex-1">
              {events?.items && events.items.length > 0 ? (
                <div className="grid gap-4">
                  {events.items.map((event) => (
                    <EventCard key={event.id} event={event} />
                  ))}
                </div>
              ) : (
                <Card>
                  <CardContent className="pt-6">
                    <p className="text-muted-foreground text-center">
                      No events found for the selected date range.
                    </p>
                  </CardContent>
                </Card>
              )}
            </div>
            <Button
              onClick={() => {
                console.log("generate invoices");
              }}
            >
              Generate Invoices
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
