import Head from "next/head";
import { Calendar } from "~/components/ui/calendar";
import { type DateRange } from "react-day-picker";

import { api } from "~/utils/api";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export default function Home() {
  const { mutate: authWithGoogleCalendar } =
    api.user.authWithGoogleCalendar.useMutation();

  const { data: events } = api.workflow.getEvents.useQuery();

  const [dateRange, setDateRange] = useState<DateRange | undefined>({
    from: new Date(2025, 5, 12),
    to: new Date(2025, 6, 15),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex h-16 items-center justify-end gap-4 p-4">
        <SignedOut>
          <SignInButton />
          <SignUpButton>
            <button className="h-10 cursor-pointer rounded-full bg-[#6c47ff] px-4 text-sm font-medium text-white sm:h-12 sm:px-5 sm:text-base">
              Sign Up
            </button>
          </SignUpButton>
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </header>
      <Calendar
        mode="range"
        defaultMonth={dateRange?.from}
        selected={dateRange}
        onSelect={setDateRange}
        className="rounded-lg border shadow-sm"
      />
      <Button
        onClick={() => {
          authWithGoogleCalendar(undefined, {
            onSuccess: (data) => window.open(data.url, "_blank"),
          });
          console.log("hi");
        }}
      >
        Google
      </Button>
      {events?.items?.map((event) => (
        <div key={event.id} className="border rounded-lg p-4">
          <h3>{event.summary}</h3>
          <p>{event.start.dateTime}</p>
        </div>
      ))}
    </>
  );
}
